server:
  port: 8013
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-13ToolCalling
  ai:
    openai:
      api-key: ${QiNiu_Api}
      base-url: https://api.qnaigc.com
      chat:
        options:
          model: gemini-3.0-flash-preview
    dashscope:
      api-key: ${ALi_Key}
      embedding:
        options:
          model: text-embedding-v4
    vectorstore:
      redis:
        initialize-schema: true
        index-name: aiops-index
        prefix: aiops-prefix
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3
      timeout: 2