server:
  port: 8005
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-05Prompt
  ai:
    openai:
      api-key: ${QiNiu_Api}
      base-url: https://api.qnaigc.com
      chat:
        options:
          model: gemini-3.0-flash-preview